sudo: false
language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - "4"
  - "5"
  - "6"
install:
  - npm install
script:
  - npm run lint
  - npm test
  - npm run postcodecover
branches:
  only:
    - master
deploy:
  provider: npm
  email: tsevdosjohn@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: tsevdos/greek-in-tech
